# Pandas is a tool for data analysis and data manipulation

## Two main data structures in Pandas
1. series  - one dimentional arrays
2. data frames - two dimentional arrays

In [2]:
import pandas as pd
import numpy as np

In [5]:
# creating an array
data = np.array([[1,4], [2,5], [3,7]])

In [7]:
# creating a dataframe
df = pd.DataFrame(data, index=['row1','row2','row3'], columns=['col1','col2'])

In [8]:
df

      col1  col2
row1     1     4
row2     2     5
row3     3     7

# Creating a DataFrame from dictionary

In [10]:
# lists

states = ['California','Taxes','Florida','New York']
population = [204456, 7123410, 1974887, 3551300]

dict_states = {'States': states, 'Population': population}

In [11]:
df_population = pd.DataFrame(dict_states)

In [12]:
df_population

       States  Population
0  California      204456
1       Taxes     7123410
2     Florida     1974887
3    New York     3551300

# Reading a DataFrame from csv file

In [17]:
df_exams = pd.read_csv('StudentsPerformance.csv')

In [18]:
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75